---
- name: Install and configure chrony clients
  hosts: chrony_clients
  become: yes

  vars:
    ntp_servers:
      - 192.168.161.71
      - 192.168.161.72

  tasks:
    - name: Install chrony
      yum:
        name: chrony
        state: latest

    - name: Enable and start chrony service
      systemd:
        name: chronyd
        enabled: yes
        state: started

    - name: Backup existing chrony configuration
      command: mv /etc/chrony.conf /etc/chrony.conf.bak
      ignore_errors: yes

    - name: Configure chrony
      template:
        src: chrony_clients.conf.j2
        dest: /etc/chrony.conf
        owner: root
        group: root
        mode: '0644'

    - name: Wait for chrony service to be active
      become: true
      systemd:
        name: chronyd
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Ensure chronyd is synchronized
      command: chronyc tracking
      register: output
      until: '"Leap status     : Normal" in output.stdout'
      retries: 5
      delay: 10

    - name: Verify NTP server synchronization
      command: chronyc sources -v
      register: sources_output

    - debug:
        var: sources_output.stdout